try:
    num = int("a")
except ValueError as e:
    print("Terjadi error: ", e)